<a href="https://colab.research.google.com/github/SanriGirdabi/Machine-Learning-Series/blob/main/Introduction_To_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


### Introduction to Tensors

## Creating tensors

In [4]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [5]:
scalar.ndim

0

In [6]:
# Get the tensor back as Python int
scalar.item()

9

In [7]:
vector = torch.tensor([9, 9])
vector

tensor([9, 9])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3073, 0.6134, 0.6345, 0.9941],
        [0.0154, 0.9914, 0.0112, 0.0066],
        [0.6322, 0.5355, 0.1242, 0.0037]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width
random_image_size_tensor

tensor([[[0.3832, 0.6248, 0.1047,  ..., 0.5629, 0.9588, 0.0786],
         [0.9167, 0.0963, 0.9490,  ..., 0.5256, 0.0384, 0.4490],
         [0.9892, 0.3896, 0.3299,  ..., 0.1037, 0.1934, 0.5156],
         ...,
         [0.4380, 0.3007, 0.7709,  ..., 0.0684, 0.1168, 0.7980],
         [0.6824, 0.9800, 0.0126,  ..., 0.0991, 0.6730, 0.5460],
         [0.8323, 0.5834, 0.8870,  ..., 0.1715, 0.8828, 0.4800]],

        [[0.8007, 0.4949, 0.2178,  ..., 0.3378, 0.7233, 0.2986],
         [0.0944, 0.6482, 0.6281,  ..., 0.7860, 0.8950, 0.8134],
         [0.8693, 0.2090, 0.3276,  ..., 0.3898, 0.1939, 0.7280],
         ...,
         [0.0596, 0.9663, 0.0753,  ..., 0.9488, 0.4897, 0.3427],
         [0.5496, 0.4319, 0.9735,  ..., 0.2706, 0.3121, 0.0542],
         [0.5491, 0.7519, 0.1156,  ..., 0.4057, 0.1136, 0.3708]],

        [[0.5525, 0.5312, 0.6899,  ..., 0.4192, 0.8345, 0.6997],
         [0.7672, 0.3352, 0.9081,  ..., 0.1387, 0.3350, 0.0257],
         [0.7729, 0.6589, 0.2324,  ..., 0.5513, 0.2240, 0.

In [20]:
random_image_size_tensor.ndim

3

In [21]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

## Zeros and ones

In [22]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors-like

In [25]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
stepped = torch.arange(start=0, end=55, step=9)
stepped

tensor([ 0,  9, 18, 27, 36, 45, 54])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.9], dtype=torch.float64, 
                               device=None, 
                               requires_grad=False)
float_32_tensor

tensor([3.0000, 6.0000, 9.9000], dtype=torch.float64)

In [29]:
float_32_tensor.dtype

torch.float64

In [30]:
int_16_tensor = torch.tensor([3, 6, 9], dtype=torch.int16, 
                               device=None, 
                               requires_grad=False)
int_16_tensor

tensor([3, 6, 9], dtype=torch.int16)

### Getting the information from tensors
1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

### Manipulating Tensors (Matrix Multiplication)

In [32]:
# Element wise
tensor = torch.tensor([1, 2, 4])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 4]) * tensor([1, 2, 4])
Equals: tensor([ 1,  4, 16])


In [33]:
# Matrix Multiplication
matrix_result = torch.matmul(tensor, tensor)
matrix_result

tensor(21)

In [35]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(21)
CPU times: user 3.57 ms, sys: 0 ns, total: 3.57 ms
Wall time: 8.59 ms


In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 167 µs, sys: 16 µs, total: 183 µs
Wall time: 191 µs


tensor(21)

In [37]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[2, 5],
                         [3, 5],
                         [2, 2]])
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [41]:
# To fix the shape and make it productable we need to transpoze one of them
print(f"tensor a shape: {tensor_A.T.shape}")
print(f"tensor b shape: {tensor_B.shape}")
print(f"the matrix product of these: {torch.matmul(tensor_A.T, tensor_B)}")
print(f"the shape of the product: {torch.matmul(tensor_A.T, tensor_B).shape}")

tensor a shape: torch.Size([2, 3])
tensor b shape: torch.Size([3, 2])
the matrix product of these: tensor([[21, 30],
        [28, 42]])
the shape of the product: torch.Size([2, 2])
