<a href="https://colab.research.google.com/github/SanriGirdabi/Machine-Learning-Series/blob/main/Introduction_To_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


### Introduction to Tensors

## Creating tensors

In [3]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [4]:
scalar.ndim

0

In [6]:
# Get the tensor back as Python int
scalar.item()

9

In [7]:
vector = torch.tensor([9, 9])
vector

tensor([9, 9])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [17]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1891, 0.7572, 0.8166, 0.1244],
        [0.5568, 0.0227, 0.3804, 0.6430],
        [0.5566, 0.1228, 0.1104, 0.8539]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width
random_image_size_tensor

tensor([[[0.2624, 0.0266, 0.2476,  ..., 0.9936, 0.7899, 0.2681],
         [0.5856, 0.7959, 0.0572,  ..., 0.8524, 0.6509, 0.2867],
         [0.4283, 0.5117, 0.5685,  ..., 0.1185, 0.8139, 0.7012],
         ...,
         [0.4165, 0.0627, 0.4088,  ..., 0.9805, 0.9447, 0.8420],
         [0.4194, 0.1077, 0.7670,  ..., 0.9272, 0.5425, 0.6661],
         [0.6360, 0.2654, 0.9137,  ..., 0.0220, 0.7952, 0.9789]],

        [[0.3032, 0.7114, 0.0013,  ..., 0.3236, 0.0795, 0.4589],
         [0.4624, 0.5753, 0.7661,  ..., 0.6758, 0.0304, 0.2138],
         [0.4259, 0.2769, 0.2328,  ..., 0.9679, 0.4216, 0.5756],
         ...,
         [0.0400, 0.2263, 0.6130,  ..., 0.9559, 0.6366, 0.5461],
         [0.4694, 0.7351, 0.9170,  ..., 0.1127, 0.2767, 0.6918],
         [0.4280, 0.7070, 0.7457,  ..., 0.1440, 0.2448, 0.0198]],

        [[0.3968, 0.1043, 0.1289,  ..., 0.1622, 0.4216, 0.9382],
         [0.2910, 0.2876, 0.0205,  ..., 0.5080, 0.7569, 0.4403],
         [0.0115, 0.7688, 0.7447,  ..., 0.3044, 0.1081, 0.

In [22]:
random_image_size_tensor.ndim

3

In [24]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

## Zeros and ones

In [27]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors-like

In [33]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
stepped = torch.arange(start=0, end=55, step=9)
stepped

tensor([ 0,  9, 18, 27, 36, 45, 54])

In [36]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [46]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.9], dtype=torch.float64, 
                               device=None, 
                               requires_grad=False)
float_32_tensor

tensor([3.0000, 6.0000, 9.9000], dtype=torch.float64)

In [47]:
float_32_tensor.dtype

torch.float64

In [48]:
int_16_tensor = torch.tensor([3, 6, 9], dtype=torch.int16, 
                               device=None, 
                               requires_grad=False)
int_16_tensor

tensor([3, 6, 9], dtype=torch.int16)

### Getting the information from tensors
1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

### Manipulating Tensors (Matrix Multiplication)