<a href="https://colab.research.google.com/github/SanriGirdabi/Machine-Learning-Series/blob/main/Introduction_To_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to Tensors

## Creating tensors

In [45]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [46]:
scalar.ndim

0

In [47]:
# Get the tensor back as Python int
scalar.item()

9

In [48]:
vector = torch.tensor([9, 9])
vector

tensor([9, 9])

In [49]:
vector.ndim

1

In [50]:
vector.shape

torch.Size([2])

In [51]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [52]:
MATRIX.ndim

2

In [53]:
MATRIX.shape

torch.Size([2, 2])

In [54]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [55]:
TENSOR.ndim

3

In [56]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [57]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1766, 0.1329, 0.5409, 0.5369],
        [0.8626, 0.1353, 0.5082, 0.1252],
        [0.2958, 0.8158, 0.0075, 0.3361]])

In [58]:
random_tensor.ndim

2

In [59]:
random_tensor.shape

torch.Size([3, 4])

In [60]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width
random_image_size_tensor

tensor([[[0.5175, 0.1772, 0.4430,  ..., 0.1126, 0.3723, 0.6326],
         [0.9601, 0.9511, 0.1716,  ..., 0.2704, 0.2264, 0.5693],
         [0.4412, 0.1791, 0.2651,  ..., 0.5614, 0.8050, 0.2254],
         ...,
         [0.4866, 0.9690, 0.5563,  ..., 0.4378, 0.4325, 0.7211],
         [0.0854, 0.4082, 0.6218,  ..., 0.4054, 0.4389, 0.2753],
         [0.1966, 0.6101, 0.1209,  ..., 0.2772, 0.8199, 0.2551]],

        [[0.1988, 0.8382, 0.6213,  ..., 0.8356, 0.0158, 0.5108],
         [0.2736, 0.4195, 0.9836,  ..., 0.7227, 0.3892, 0.3605],
         [0.5728, 0.4511, 0.0636,  ..., 0.8551, 0.1569, 0.9172],
         ...,
         [0.1697, 0.5349, 0.8559,  ..., 0.2061, 0.4949, 0.8714],
         [0.3717, 0.6490, 0.4421,  ..., 0.9083, 0.9516, 0.3754],
         [0.0902, 0.8705, 0.4206,  ..., 0.8940, 0.2323, 0.1298]],

        [[0.7975, 0.2838, 0.2022,  ..., 0.4082, 0.8240, 0.4417],
         [0.6184, 0.7072, 0.6389,  ..., 0.0391, 0.6716, 0.0787],
         [0.0414, 0.6743, 0.7197,  ..., 0.1207, 0.9064, 0.

In [61]:
random_image_size_tensor.ndim

3

In [62]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

## Zeros and ones

In [63]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [65]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors-like

In [66]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
stepped = torch.arange(start=0, end=55, step=9)
stepped

tensor([ 0,  9, 18, 27, 36, 45, 54])

In [68]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [69]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.9], dtype=torch.float64, 
                               device=None, 
                               requires_grad=False)
float_32_tensor

tensor([3.0000, 6.0000, 9.9000], dtype=torch.float64)

In [70]:
float_32_tensor.dtype

torch.float64

In [71]:
int_16_tensor = torch.tensor([3, 6, 9], dtype=torch.int16, 
                               device=None, 
                               requires_grad=False)
int_16_tensor

tensor([3, 6, 9], dtype=torch.int16)

### Getting the information from tensors
1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

## Manipulating Tensors (Matrix Multiplication)

In [72]:
# Element wise
tensor = torch.tensor([1, 2, 4])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 4]) * tensor([1, 2, 4])
Equals: tensor([ 1,  4, 16])


In [73]:
# Matrix Multiplication
matrix_result = torch.matmul(tensor, tensor)
matrix_result

tensor(21)

In [74]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(21)
CPU times: user 412 µs, sys: 0 ns, total: 412 µs
Wall time: 417 µs


In [75]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 74 µs, sys: 8 µs, total: 82 µs
Wall time: 86.1 µs


tensor(21)

In [76]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[2, 5],
                         [3, 5],
                         [2, 2]])
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [77]:
# To fix the shape and make it productable we need to transpoze one of them
print(f"tensor a shape: {tensor_A.T.shape}")
print(f"tensor b shape: {tensor_B.shape}")
print(f"the matrix product of these: {torch.matmul(tensor_A.T, tensor_B)}")
print(f"the shape of the product: {torch.matmul(tensor_A.T, tensor_B).shape}")

tensor a shape: torch.Size([2, 3])
tensor b shape: torch.Size([3, 2])
the matrix product of these: tensor([[21, 30],
        [28, 42]])
the shape of the product: torch.Size([2, 2])


## Finding the min, max, mean, sum etc

In [78]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [79]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [80]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [81]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [82]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [83]:
torch.sum(x[3 :])

tensor(427)

In [85]:
# Fİnd the position in the tensor that has the minimum value with argmin() --> return the position
x.argmin()

tensor(0)

In [86]:
x.argmax()

tensor(9)

## Reshaping, Stacking, Squeezing, Unsqueezing Tensors

In [92]:
X = torch.arange(1., 13.)
X

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [93]:
# Add an extra dimension
X_reshaped = X.reshape(4, 3)
X_reshaped

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [97]:
# Change the view
z = X.view(1, 12)
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [104]:
X.clone().detach().reshape(1, 12)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [106]:
# When you change a view, it changes the source as well!
z[:, 0] = 55
z, X

(tensor([[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [113]:
# Stack tensors on top of each other
x_stacked = torch.stack([X, X, X], dim=0)
x_stacked

tensor([[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [114]:
x_stacked2 = torch.stack([X, X, X], dim=1)
x_stacked2

tensor([[55., 55., 55.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.],
        [11., 11., 11.],
        [12., 12., 12.]])

In [121]:
X.reshape(1, 1, 12)

tensor([[[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]])

In [122]:
X.reshape(1, 1, 12).squeeze()

tensor([55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [130]:
X.unsqueeze(0)

tensor([[55.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [131]:
X.unsqueeze(1)

tensor([[55.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])

In [144]:
#permute rearranges the dimensions of a specified order
x_stacked.shape
x_reshaped_again = x_stacked.reshape(2, 9, 2)
x_reshaped_again


tensor([[[55.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.],
         [55.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.],
         [55.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [153]:
torch.permute(x_reshaped_again, (0, 2, 1))

tensor([[[55.,  3.,  5.,  7.,  9., 11., 55.,  3.,  5.],
         [ 2.,  4.,  6.,  8., 10., 12.,  2.,  4.,  6.]],

        [[ 7.,  9., 11., 55.,  3.,  5.,  7.,  9., 11.],
         [ 8., 10., 12.,  2.,  4.,  6.,  8., 10., 12.]]])

In [158]:
torch.permute(x_reshaped_again, (1, 2, 0))

tensor([[[55.,  7.],
         [ 2.,  8.]],

        [[ 3.,  9.],
         [ 4., 10.]],

        [[ 5., 11.],
         [ 6., 12.]],

        [[ 7., 55.],
         [ 8.,  2.]],

        [[ 9.,  3.],
         [10.,  4.]],

        [[11.,  5.],
         [12.,  6.]],

        [[55.,  7.],
         [ 2.,  8.]],

        [[ 3.,  9.],
         [ 4., 10.]],

        [[ 5., 11.],
         [ 6., 12.]]])